### PR TITLE
fix: CORS errors

### LINKED ISSUE #62: CORS errors in production
**Describe the bug**
There are CORS errors on request from front app

**To Reproduce**
Call API from centurio.app

**Screenshots**
image

### PR DESCRIPTION
**Pull request by acroquelois**

### CODE REVIEW

**Comment by acroquelois** [comment]
This pull request is an assumption about the source of the bug

**Comment by octogene** [comment]
I think it is the right assumption about the cause of the error. The recent config change in the DNS followed by the Vercel migration is forcing a redirect on www.centurio.app when accessing the root domain.

File: centurio-restapi/src/main/kotlin/fr/hadaly/module/Cors.kt [hunk 1]
```diff
@@ -18,6 +18,7 @@ fun Application.corsModule() {
             allowCredentials = true
         } else {
             val frontHost = environment.config.property("ktor.deployment.front_host").getString()
+            host(frontHost, subDomains = listOf("www"))
```
Comment (octogene) [inline centurio-restapi/src/main/kotlin/fr/hadaly/module/Cors.kt]: Good but you are removing the constraint for the https scheme which is not good idea, you can keep both options.

**Review by octogene — CHANGES_REQUESTED** [review]

File: centurio-restapi/src/main/kotlin/fr/hadaly/module/Cors.kt (hunk 1 above)
Comment (acroquelois) [reply centurio-restapi/src/main/kotlin/fr/hadaly/module/Cors.kt]: The constraint for https scheme stay present on the next line. In the documentation it seems like we can do this way:
https://ktor.io/docs/cors.html#advanced

Comment (octogene) [reply centurio-restapi/src/main/kotlin/fr/hadaly/module/Cors.kt]: I don't see that calling two times the method will not override the first call. I think,  the commented lines are there to show some examples.
And even if calling the method was adding each time a new rule, it would mean that the first time you authorize www.HOST for all schemes and second times HOST for https schemes, which in fact would mean that you allow the http scheme for the www subdomain, which is not what we want.
Furthermore, there is no reason to put this on two lines as it concerns the same host.

Comment (acroquelois) [reply centurio-restapi/src/main/kotlin/fr/hadaly/module/Cors.kt]: Indeed, it would be override the config. I change that to put on the same line.

**Review by octogene — APPROVED** [review]
